---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: villain
  labels:
    app: villain
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: villain
  template:
    metadata:
      labels:
        app: villain
    spec:
      containers:
        - name: villain
          image: workshop/villain:1.1
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: IfNotPresent
          env:
            - name: QUARKUS_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: supes-config
                  key: database
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: supes-database-secret
                  key: username
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supes-database-secret
                  key: password
